#!/bin/bash

# Premise: Find the largest palindrome generated by a multiple of two 3 digit numbers.
# Answer: 906609
function palindromeCheck {
    reversed="$(echo $1|rev)"
    if [ "$1" -eq "$reversed" ]
    then
        palindrome=true
    else
        palindrome=false
    fi
}

# Populating 2 lists with integers from 111 - 999
for i in $(seq 111 999)
do
    x[$((i-111))]=$i
done

for i in $(seq 111 999)
do
    y[$((i-111))]=$i
done
max_palindrome=0

#Finding the max palindrome:
for p in ${x[@]}
do
    for q in ${y[@]}
    do
        a=$((p*q))
	palindromeCheck $a
	if [ $palindrome = true ]
	then
	    if [ $max_palindrome -lt $a ]
	    then 
	        max_palindrome=$a
	    fi
	fi
    done

    # Remove pth element from array x and y:
    unset x[p-111]
    unset y[p-111]
    echo $p : $max_palindrome
done
echo $max_palindrome
